# Generated by Django 2.2.6 on 2019-10-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloalma', models.CharField(max_length=30)),
                ('capacidadalma', models.CharField(max_length=10)),
                ('tipoalma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelofuente', models.CharField(max_length=30)),
                ('marcafuente', models.CharField(max_length=30)),
                ('wattsfuente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelogabinete', models.CharField(max_length=30)),
                ('tamanogabinete', models.CharField(max_length=5)),
                ('marcagabinete', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaplaca', models.CharField(max_length=30)),
                ('modeloplaca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generacionproce', models.CharField(max_length=30)),
                ('modeloproce', models.CharField(max_length=30)),
                ('marcaproce', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaram', models.CharField(max_length=30)),
                ('modeloram', models.CharField(max_length=30)),
                ('memoriaram', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelovideo', models.CharField(max_length=30)),
                ('marcavideo', models.CharField(max_length=30)),
                ('generacionvideo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Almacenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Almacenamiento')),
                ('Fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Fuente')),
                ('Gabinete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Gabinete')),
                ('PlacaMadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.PlacaMadre')),
                ('Procesador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Procesador')),
                ('Ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Ram')),
                ('TarjetaVideo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.TarjetaVideo')),
            ],
        ),
    ]
